telegram_bot:
  token: $TELEGRAM_BOT_TOKEN

database:
  csv:
    columns: 
      - phone
      - tg_user_id
      - tg_username
      - wh_user_id


whatsapp_bot:
  id_instance: $WHATSAPP_BOT_ID_INSTANCE
  token_instance: $WHATSAPP_BOT_API_TOKEN_INSTANCE
